### ISSUE TITLE
Add lazy loading

### ISSUE THREAD

**Issue by arthurRbr** [wishrd/angular-universal-i18n-starter#1]
Hi, 

Any idea how to implement the rendering of lazy-loaded child routes like the two following modules do?
```
@nguniversal/express-engine
@nguniversal/module-map-ngfactory-loader
```

Thanks a lot!

**Comment by wishrd** [comment]
Hi,

the list in your message is empty, you mean this? https://angular.io/guide/universal#app-server-module

Check `ModuleMapLoaderModule`from `@nguniversal/module-map-ngfactory-loader` and try to configure the `AppServerModule` and `server.ts` like Universal's Guide.

I'll try to update the starter with this fix soon, thank you for reporting!

**Comment by arthurRbr** [comment]
Just saw the last commits, thanks a lot!

Quick question: any reason why you're not using `@nguniversal/express-engine` as a wrapper around renderModuleFactory?

thanks

**Comment by wishrd** [comment]
I thought I could not indicate the template correctly to ngExpressEngine but I was wrong. Just a bit of refactoring :)

Check the last commit.

Anyway, i have pending refactoring the locale management in `server.ts` (i don't like hardcoded locales).

Regards!

**Comment by arthurRbr** [comment]
Great work, thanks :)
